# Generated by Django 3.2.6 on 2021-08-26 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1999-01-23'),
            preserve_default=False,
        ),
    ]
